### ISSUE TITLE
Update arsh4.files() to read from a `datadir/meta.yaml` file

### ISSUE THREAD

**Issue by lianos** [denalitherapeutics/archs4#2]
The names of the files in the archs4 `datadir` are hard coded in the `archs4.files` function.

As these files are updated from the ARCHS4 resource, their names will change. ie. the first mouse transcript-level hdf5 file was called `"mouse_hiseq_eid_1.0.h5"`, but the second version is `"mouse_hiseq_transcript_v2.h5"`.

In order to accommodate these changes, the `datadir` can have a `meta.yaml` file with a `files` section, which can look something like this:

```
files:
  mouse_transcript:
    filename: mouse_hiseq_transcript_v2.h5
    description: "mouse-level transcript quantitation downloaded on 3/3/2018"
  mouse_gene:
    filename: mouse_matrix.h5
    description: "mouse-level gene quantitation downloaded on ..."
  ...
```
